// "use client";
import "./globals.css";
import { Inter } from "next/font/google";
// import Header from "@/components/Header/Header";
import Footer from "./footer/page";
import Header from "./header/page";

// import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

//  const metadata = {
//   title: "Vzone Solutions",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    // `${inter.className} bg-gray-200`
    <html lang="en">
      <head>
        <title> VZone Solutions</title>
      </head>
      <body className={inter.className}>
        {/* <div class="bg-[url('/vzone-bg.png')]"> */}
        <Header />
        {children}
        <Footer />

        {/* </div> */}
      </body>
    </html>
  );
}
